name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    
    # Checkout repository
    - uses: actions/checkout@v2
    
    # Setup Node.js environment
    - uses: actions/setup-node@v2
      with:
        node-version: '20.16'
    
    # Cache Node.js modules (includes Playwright)
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Cache Playwright browsers
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    # Install dependencies (includes Playwright)
    - name: Install dependencies
      run: npm ci
    
    # Check if Playwright is already installed from cache
    - name: Check Playwright install
      run: |
        if [ ! -d ~/.cache/ms-playwright ]; then
          echo "Playwright binaries not cached, installing..."
          npx playwright install --with-deps
        else
          echo "Playwright is already cached, skipping installation."
        fi
    
    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

    # Upload Playwright report as an artifact
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
