name: Playwright Script
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  Cached-Playwright-Script:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - name: Check out repository code
        uses: actions/checkout@v3
      
      # Cache Playwright browsers
      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Install Playwright and its dependencies if cache miss
      - name: Install Playwright deps
        run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      
      # Run Playwright script
      - name: Run Playwright script
        run: node playwright-script.js
