name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    
    # Checkout repository
    - uses: actions/checkout@v2
    
    # Setup Node.js environment
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci
    
    # Install Playwright dependencies
    - name: Install Playwright
      run: npx playwright install --with-deps
    
    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

    # Upload Playwright report as an artifact
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # Upload videos on failure
    - name: Upload Playwright videos
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-videos
        path: test-results/
        retention-days: 7  
